name: 'read-app-metadata'
description: 'Read ArgoCD Applications metadata'
author: 'Ceska sporitelna, a.s.'
inputs:
  dir:
    required: false
    description: Root directory, where files are located. Default is current directory.
  files:
    required: false
    description: Optional glob pattern, a multiline list.
  recursive:
    required: false
    description: Turns on recursive search of the dir. Unused when files input is used.
    default: 'false'
outputs:
  files:
    description: |-
      JSON list of found file names.
  apps:
    description: |-
      JSON list of all parsed metadata.
  app:
    description: |-
      JSON with single application. Only if exactly one app was found.
  file:
    description: |-
      File name. Only if exactly one app was found.
  name:
    description: |-
      Application name. Only if exactly one app was found.
  repoURL:
    description: |-
      Helm chart repository URL. Only if exactly one app was found.
  repoName:
    description: |-
      Artifactory repository name. Assumes repoURL points to an Artifactory. Only if exactly one app was found.
  chart:
    description: |-
      Chart name. Only if exactly one app was found.
  version:
    description: |-
      Chart version. Only if exactly one app was found.
  values:
    description: |-
      Helm values, as a string. It will probably contain YAML. Optional. Only if exactly one app was found.
runs:
  using: 'node20'
  main: 'dist/index.js'
