# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types:
  - pre-commit
  - commit-msg
default_stages: [pre-commit]
repos:
-   repo: meta
    hooks:
    -   id: check-useless-excludes

-   repo: https://github.com/jorisroovers/gitlint
    rev:  v0.19.1
    hooks:
    -   id: gitlint
        stages: [ commit-msg ]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-yaml
        #Helm Chart templates aren't truly yaml files
        exclude: ^chart/templates/
    -   id: check-xml
    -   id: check-json
