name: Approve Snapshot PR
run-name: Approve PR - ${{ github.event.pull_request.number }}

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  approvePR:
    runs-on: csas-linux
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    env:
      GH_TOKEN: ${{ github.token }}
    if: >
      github.actor == 'csas-dev-release-please[bot]' &&
      startsWith(github.event.pull_request.title, 'chore(master): release') &&
      github.event.pull_request.commits == 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Approve PR
        run: |
          gh pr review --approve ${{ github.event.pull_request.number }}

      - name: Automerge enabled
        run: |
          gh pr merge --auto --rebase ${{ github.event.pull_request.number }}
