name: Deploy to Deva

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  SetVersionOnOPS:
    if: >
      ( contains(github.event_name, 'release') && contains(github.event.action, 'published') ) &&
      github.actor == 'csas-dev-release-please[bot]'
    runs-on: csas-linux
    steps:
      - name: Trigger Workflow
        run: |

          version=${{ env.VERSION }}

          output_file="output.txt"
          branch_name=$(echo "${{env.BRANCH_NAME}}" | sed "s|env/||g" | tr -d "\"")
          echo "version=${version#v} GITHUB_REPOSITORY=${GITHUB_REPOSITORY#*/*-} branch_name=${branch_name}"

          curl -o "${output_file}" -X POST -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{secrets.TECHUSERPAT}}" \
            https://api.github.com/repos/csas-ops/OPS_REPO_NAHRAD/actions/workflows/${{ env.WORKFLOW_NAME }}/dispatches \
            -d '{"ref":"refs/heads/master","inputs":{"appName":"'"${GITHUB_REPOSITORY#*/*-}"'","newVersion":"'"${version#v}"'","envName":"'"${branch_name}"'","labelName":"${{ env.LABEL_NAME }}"}}' -s
          cat ${output_file}
          if [[ $(jq '.message' "${output_file}" | wc -l) -gt 0 ]]; then
            echo "::error::Error message in curl output - $(jq '.message' ${output_file})"
            exit 1
          fi
        env:
          WORKFLOW_NAME: "setVersion.yml"
          BRANCH_NAME: "env/deva"
          LABEL_NAME: "LABEL_NAME_NAHRAD"
          VERSION: ${{ steps.version.outputs.version }}
          APP_NAME: "APP_NAME_NAHRAD"