default_install_hook_types:
  - pre-commit
  - commit-msg
default_stages: [pre-commit]
repos:
  - repo: meta
    hooks:
    -   id: check-useless-excludes

  - repo: https://github.com/jorisroovers/gitlint
    rev:  v0.19.1
    hooks:
    -   id: gitlint
        stages: [ commit-msg ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: check-xml
    -   id: check-json

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.76.0
    hooks:
      - id: terraform_fmt
      # Hledání chyb v kódu pomocí statické analýzy kodu
      - id: terraform_tflint
        args:
          - --args=--module
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
      # Hledání security chyb v kódu pomocí statické analýzy kodu
      - id: terraform_checkov
        args:
          - --args=--skip-check CKV_GIT_5 #nechceme aby 2 delali approvals
          - --args=--skip-check CKV_GIT_1 #Mame i Internal repa, nejen Private
          - --args=--skip-check CKV_GIT_6 #Sign commity zatim nepouzivame TBD az bude novejsi git bash vCS vyzkouset. Plus diskutuji jeste s Markem, co si o tom mysli
          - --args=--skip-check CKV_GIT_4 #TBD musis doresit jak predem encryptnout data
          - --args=--skip-check CKV_SECRET_6
          #https://docs.github.com/en/rest/actions/secrets#create-or-update-an-organization-secret,
          #https://github.com/integrations/terraform-provider-github/pull/807,
          #https://github.com/integrations/terraform-provider-github/issues/888
          - --args=--quiet
          - --args=--skip-download

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint
        exclude: CHANGELOG.md

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
      - id: shfmt