name: Build TF module

on:
  workflow_dispatch:
  release:
    types: [published]

permissions: read-all

jobs:
  buildTFModule:
    runs-on: csas-linux

    #need pull-request write for create/update comment in Pull Request
    permissions:
      contents: read

    env:
      # Base URL to JFrog artifactory
      ARTIFACTORY_URL: https://artifactory.csin.cz
      # Project package in Artifactory
      REPOSITORY_NAME: MODULE_REPO_NAHRAD

    steps:
      - name: Wait for finish create documentation
        run: sleep 20

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Whole history is needed for Sonar scan

      - name: Download JFrog cli
        #if: (contains(github.head_ref, 'release-please') || github.event_name == 'workflow_dispatch') && inputs.BUILD_LIBRARY == false
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ env.ARTIFACTORY_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
        with:
          download-repository: releases-jfrog-io/jfrog-cli

      - name: Test JFrog cli
        #if: (contains(github.head_ref, 'release-please') || github.event_name == 'workflow_dispatch') && inputs.BUILD_LIBRARY == false
        run: |
          jf rt ping

      - name: jfrog terraform-config
        run: jf tfc --repo-deploy ${{env.REPOSITORY_NAME}}

      - name: jfrog terraform-publish
        run: |
          MODULENAME=$(echo "${{github.event.repository.name}}" | cut -d - -f 3-)
          jf tf p --namespace=github --provider=github --tag=${{ github.event.release.name }} --exclusions="*examples*"