name: Lint

on:
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: reviewdog/action-eslint@v1
        with:
          fail_on_error: true
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'github-check' }}
