name: Test

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: csas-linux
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Whole history is needed for Sonar scan

      # Login
      - name: Artifactory login
        uses: csas-actions/artifactory-login@v1
        with:
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

      # Setup
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: npm

      # Test
      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run all

      # Scan
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonar.csin.cz
