name: Update README

on:
  push:
    branches-ignore:
      - update-cli--**
      - update-readme--**
    paths:
      - README.md
      - action.yml
      - .github/workflows/update-readme.yml
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update README.md
        uses: mdvorak/update-action-readme@v1

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "chore(docs): update README.md tables on ${{ github.ref_name }}"
          commit-message: "docs(docs): updated README.md inputs table"
          body: "Updated README.md inputs/outputs tables, according to action.yml file"
          branch: update-readme--${{ github.ref_name }}
          delete-branch: true
          labels: bot,documentation
