name: Update dist/

on:
  push:
    branches-ignore: [ "update-dist--**" ]
  workflow_dispatch:

jobs:
  update-dist:
    name: Update dist
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Rebuild the dist/ directory
        run: |
          npm run build
          npm run package

      - name: Fix vercel/ncc CRLF output
        run: |
          # See https://github.com/vercel/ncc/issues/638
          sed -i 's/\x0D$//' ./dist/index.js

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "chore(dist): update dist/ on ${{ github.ref_name }}"
          commit-message: "chore(dist): update dist/"
          body: "Updated dist/ built distributable files"
          branch: update-dist--${{ github.ref_name }}
          delete-branch: true
          labels: bot,dist
